/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finstereflure;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Amandine S
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceBis
     */
    public Interface() {
        initComponents();
        jTitre.setIcon(new ImageIcon("./img/logo_finstere_grand.gif"));   //image titre jeu
        //griser les boutons :
        jNewGame.setEnabled(false);
        jContinue.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCreditPage = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBackCredits = new javax.swing.JButton();
        jConnexionPage = new javax.swing.JFrame();
        jBG = new javax.swing.JPanel();
        jPseudoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jOkConnexion = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jShowPassword = new javax.swing.JLabel();
        jShowButton = new javax.swing.JButton();
        jBackConnexion = new javax.swing.JButton();
        jNewAccount = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jConfirmPasswordField = new javax.swing.JPasswordField();
        jShowConfirm = new javax.swing.JButton();
        jShowConfirmPassword = new javax.swing.JLabel();
        jErrorLabel = new javax.swing.JLabel();
        jConfigurationPage = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jConfigLeft = new javax.swing.JPanel();
        jPseudoLeft = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSelecLeft = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jColorLeft = new javax.swing.JComboBox<>();
        jPionImageLeft = new javax.swing.JLabel();
        jConfigRight = new javax.swing.JPanel();
        jPseudoRight = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSelecRight = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jColorRight = new javax.swing.JComboBox<>();
        jPionImageRight = new javax.swing.JLabel();
        jAdvancedCheck = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jStartButton = new javax.swing.JButton();
        jBackConfiguration = new javax.swing.JButton();
        jMenuPrincipal = new javax.swing.JPanel();
        jTitre = new javax.swing.JLabel();
        jNewGame = new javax.swing.JButton();
        jContinue = new javax.swing.JButton();
        jPrevious = new javax.swing.JButton();
        jCredit = new javax.swing.JButton();
        jPseudo = new javax.swing.JLabel();
        jConnexion = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 240, 118));
        jLabel4.setText("CREDITS");

        jLabel5.setText("MERCI AAAAAAAAAAAAAAAAAAAAAAAAAAAA");

        jBackCredits.setBackground(new java.awt.Color(0, 18, 2));
        jBackCredits.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jBackCredits.setForeground(new java.awt.Color(249, 240, 118));
        jBackCredits.setText("←");
        jBackCredits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackCreditsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(566, 566, 566))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jBackCredits)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jBackCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(99, 99, 99)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jCreditPageLayout = new javax.swing.GroupLayout(jCreditPage.getContentPane());
        jCreditPage.getContentPane().setLayout(jCreditPageLayout);
        jCreditPageLayout.setHorizontalGroup(
            jCreditPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jCreditPageLayout.setVerticalGroup(
            jCreditPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jBG.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 240, 118));
        jLabel1.setText("PSEUDO :");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 240, 118));
        jLabel2.setText("PASSWORD :");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 240, 118));
        jLabel3.setText("CONNEXION");

        jOkConnexion.setBackground(new java.awt.Color(0, 18, 2));
        jOkConnexion.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jOkConnexion.setForeground(new java.awt.Color(249, 240, 118));
        jOkConnexion.setText("OK");
        jOkConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOkConnexionMouseClicked(evt);
            }
        });

        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });

        jShowPassword.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jShowPassword.setForeground(new java.awt.Color(255, 255, 255));

        jShowButton.setBackground(new java.awt.Color(0, 50, 7));
        jShowButton.setForeground(new java.awt.Color(249, 240, 118));
        jShowButton.setText("👁");
        jShowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jShowButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jShowButtonMouseReleased(evt);
            }
        });

        jBackConnexion.setBackground(new java.awt.Color(0, 18, 2));
        jBackConnexion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBackConnexion.setForeground(new java.awt.Color(249, 240, 118));
        jBackConnexion.setText("←");
        jBackConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackConnexionMouseClicked(evt);
            }
        });

        jNewAccount.setBackground(new java.awt.Color(0, 18, 2));
        jNewAccount.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jNewAccount.setForeground(new java.awt.Color(249, 240, 118));
        jNewAccount.setText("NEW ACCOUNT");
        jNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNewAccountMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 240, 118));

        jShowConfirm.setBackground(new java.awt.Color(0, 50, 7));
        jShowConfirm.setForeground(new java.awt.Color(249, 240, 118));
        jShowConfirm.setText("👁");
        jShowConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jShowConfirmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jShowConfirmMouseReleased(evt);
            }
        });

        jShowConfirmPassword.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jShowConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));

        jErrorLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jBGLayout = new javax.swing.GroupLayout(jBG);
        jBG.setLayout(jBGLayout);
        jBGLayout.setHorizontalGroup(
            jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createSequentialGroup()
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBackConnexion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField)
                            .addComponent(jConfirmPasswordField)
                            .addComponent(jPseudoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jShowPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jShowConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jBGLayout.createSequentialGroup()
                                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jNewAccount))
                                .addGap(0, 71, Short.MAX_VALUE))
                            .addComponent(jErrorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jShowButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jShowConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createSequentialGroup()
                        .addComponent(jOkConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jBGLayout.setVerticalGroup(
            jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jBackConnexion))
                .addGap(4, 4, 4)
                .addComponent(jErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPseudoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jShowButton))
                .addGap(8, 8, 8)
                .addComponent(jShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jShowConfirm)
                    .addComponent(jConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jShowConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewAccount)
                    .addComponent(jOkConnexion))
                .addContainerGap())
        );

        javax.swing.GroupLayout jConnexionPageLayout = new javax.swing.GroupLayout(jConnexionPage.getContentPane());
        jConnexionPage.getContentPane().setLayout(jConnexionPageLayout);
        jConnexionPageLayout.setHorizontalGroup(
            jConnexionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jConnexionPageLayout.setVerticalGroup(
            jConnexionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        jConfigLeft.setBackground(new java.awt.Color(51, 153, 0));
        jConfigLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPseudoLeft.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jPseudoLeft.setForeground(new java.awt.Color(249, 240, 118));
        jPseudoLeft.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 240, 118));
        jLabel7.setText("PLAYER / IA");

        jSelecLeft.setBackground(new java.awt.Color(0, 18, 2));
        jSelecLeft.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jSelecLeft.setForeground(new java.awt.Color(249, 240, 118));
        jSelecLeft.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Human", "IA" }));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 240, 118));
        jLabel9.setText("PLAYER COLOR");

        jColorLeft.setBackground(new java.awt.Color(0, 18, 2));
        jColorLeft.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jColorLeft.setForeground(new java.awt.Color(249, 240, 118));
        jColorLeft.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Brown", "Gray", "Green", "Purple", "Red", "Yellow" }));
        jColorLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorLeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jConfigLeftLayout = new javax.swing.GroupLayout(jConfigLeft);
        jConfigLeft.setLayout(jConfigLeftLayout);
        jConfigLeftLayout.setHorizontalGroup(
            jConfigLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConfigLeftLayout.createSequentialGroup()
                .addGroup(jConfigLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPseudoLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jConfigLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSelecLeft, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConfigLeftLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(jConfigLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConfigLeftLayout.createSequentialGroup()
                        .addGroup(jConfigLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jColorLeft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConfigLeftLayout.createSequentialGroup()
                                .addComponent(jPionImageLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConfigLeftLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(175, 175, 175))))
        );
        jConfigLeftLayout.setVerticalGroup(
            jConfigLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConfigLeftLayout.createSequentialGroup()
                .addComponent(jPseudoLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jSelecLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jColorLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPionImageLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );

        jConfigRight.setBackground(new java.awt.Color(51, 153, 0));
        jConfigRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPseudoRight.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jPseudoRight.setForeground(new java.awt.Color(249, 240, 118));
        jPseudoRight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 240, 118));
        jLabel8.setText("PLAYER / IA");

        jSelecRight.setBackground(new java.awt.Color(0, 18, 2));
        jSelecRight.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jSelecRight.setForeground(new java.awt.Color(249, 240, 118));
        jSelecRight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Human", "IA" }));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(249, 240, 118));
        jLabel10.setText("PLAYER COLOR");

        jColorRight.setBackground(new java.awt.Color(0, 18, 2));
        jColorRight.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jColorRight.setForeground(new java.awt.Color(249, 240, 118));
        jColorRight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Brown", "Gray", "Green", "Purple", "Red", "Yellow" }));
        jColorRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jConfigRightLayout = new javax.swing.GroupLayout(jConfigRight);
        jConfigRight.setLayout(jConfigRightLayout);
        jConfigRightLayout.setHorizontalGroup(
            jConfigRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConfigRightLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jConfigRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPseudoRight, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jConfigRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSelecRight, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConfigRightLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(jConfigRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jConfigRightLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPionImageRight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jColorRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(211, 211, 211))
            .addGroup(jConfigRightLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jConfigRightLayout.setVerticalGroup(
            jConfigRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConfigRightLayout.createSequentialGroup()
                .addComponent(jPseudoRight, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jSelecRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jColorRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPionImageRight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jAdvancedCheck.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jAdvancedCheck.setForeground(new java.awt.Color(249, 240, 118));
        jAdvancedCheck.setText("ADVANCED MODE");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(249, 240, 118));
        jLabel11.setText("SELECTION");

        jStartButton.setBackground(new java.awt.Color(0, 18, 2));
        jStartButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 39)); // NOI18N
        jStartButton.setForeground(new java.awt.Color(249, 240, 118));
        jStartButton.setText("START");
        jStartButton.setBorder(null);
        jStartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStartButtonMouseClicked(evt);
            }
        });

        jBackConfiguration.setBackground(new java.awt.Color(0, 18, 2));
        jBackConfiguration.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBackConfiguration.setForeground(new java.awt.Color(249, 240, 118));
        jBackConfiguration.setText("←");
        jBackConfiguration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackConfigurationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jConfigLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jConfigRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jAdvancedCheck)
                        .addGap(512, 512, 512))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(524, 524, 524))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jBackConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(548, 548, 548))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jBackConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jConfigRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jConfigLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jAdvancedCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jConfigurationPageLayout = new javax.swing.GroupLayout(jConfigurationPage.getContentPane());
        jConfigurationPage.getContentPane().setLayout(jConfigurationPageLayout);
        jConfigurationPageLayout.setHorizontalGroup(
            jConfigurationPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jConfigurationPageLayout.setVerticalGroup(
            jConfigurationPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuPrincipal.setBackground(new java.awt.Color(0, 102, 0));

        jNewGame.setBackground(new java.awt.Color(0, 18, 2));
        jNewGame.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 39)); // NOI18N
        jNewGame.setForeground(new java.awt.Color(249, 240, 118));
        jNewGame.setText("NEW GAME");
        jNewGame.setBorder(null);
        jNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNewGameMouseClicked(evt);
            }
        });

        jContinue.setBackground(new java.awt.Color(0, 18, 2));
        jContinue.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 39)); // NOI18N
        jContinue.setForeground(new java.awt.Color(249, 240, 118));
        jContinue.setText("CONTINUE");
        jContinue.setBorder(null);

        jPrevious.setBackground(new java.awt.Color(0, 18, 2));
        jPrevious.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 34)); // NOI18N
        jPrevious.setForeground(new java.awt.Color(249, 240, 118));
        jPrevious.setText("PREVIOUS CHAT");
        jPrevious.setBorder(null);

        jCredit.setBackground(new java.awt.Color(0, 18, 2));
        jCredit.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 34)); // NOI18N
        jCredit.setForeground(new java.awt.Color(249, 240, 118));
        jCredit.setText("CREDITS");
        jCredit.setBorder(null);
        jCredit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCreditMouseClicked(evt);
            }
        });

        jPseudo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jPseudo.setForeground(new java.awt.Color(249, 240, 118));
        jPseudo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPseudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jConnexion.setBackground(new java.awt.Color(0, 18, 2));
        jConnexion.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jConnexion.setForeground(new java.awt.Color(249, 240, 118));
        jConnexion.setText("CONNEXION");
        jConnexion.setBorder(null);
        jConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jConnexionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jMenuPrincipalLayout = new javax.swing.GroupLayout(jMenuPrincipal);
        jMenuPrincipal.setLayout(jMenuPrincipalLayout);
        jMenuPrincipalLayout.setHorizontalGroup(
            jMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPrincipalLayout.createSequentialGroup()
                .addGroup(jMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jMenuPrincipalLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1111, 1111, 1111))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMenuPrincipalLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jMenuPrincipalLayout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addGroup(jMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jMenuPrincipalLayout.createSequentialGroup()
                                .addComponent(jTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jMenuPrincipalLayout.setVerticalGroup(
            jMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOkConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOkConnexionMouseClicked

        if (jConfirmPasswordField.isVisible()) {    //si nouveau compte (car confirmation visible)
            //comparaison des deux password
            String p1 = jPasswordField.getText();
            String p2 = jConfirmPasswordField.getText();
            boolean b = p1.equals(p2);
            if (b) {    // si password et confirmation identiques
                if (jOkConnexion.isEnabled()) {
                    jConnexionPage.dispose();               //ferme la fenêtre popup de connexion
                    jPseudo.setText(jPseudoField.getText());//inscrit le pseudo
                    jConnexion.setText("DECONNEXION");      //change le bouton de connexion
                }
            } else {    //si passwords différents 
                jErrorLabel.setText("Passwords are not similar");
            }

        } else {    //sinon (si simple connexion sans nouveau compte
            if (jOkConnexion.isEnabled()) {
                jConnexionPage.dispose();                   //ferme la fenêtre popup de connexion
                jPseudo.setText(jPseudoField.getText());    //inscrit le pseudo
                jConnexion.setText("DECONNEXION");          //change le bouton de connexion
            }
        }

        //débloquer boutons game
        jNewGame.setEnabled(true);
        jContinue.setEnabled(true);
    }//GEN-LAST:event_jOkConnexionMouseClicked

    private void jConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConnexionMouseClicked

        //réinitialisation de la page
        jConnexionPage.setResizable(false);
        jLabel3.setText("CONNEXION");
        jNewAccount.setVisible(true);
        jNewGame.setEnabled(false);
        jContinue.setEnabled(false);

        boolean b = jConnexion.getText().equals("CONNEXION");
        if (b) {    //si le bouton = connexion
            //clear les champs
            jPasswordField.setText("");
            jPseudoField.setText("");
            jOkConnexion.setEnabled(false);
            jShowConfirm.setVisible(false);
            jConfirmPasswordField.setVisible(false);
            jLabel6.setText("");
            jErrorLabel.setText("");
            jConfirmPasswordField.setText("");
            //apparition de la fenêtre
            jConnexionPage.setVisible(true);
            jConnexionPage.requestFocusInWindow();
            jConnexionPage.pack();
        } else {    //sinon, si le bouton = déconnexion
            jPseudo.setText("");                //clear du champ du pseudo
            jConnexion.setText("CONNEXION");    //changement du bouton de deconnexion
        }


    }//GEN-LAST:event_jConnexionMouseClicked

    private void jCreditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCreditMouseClicked

        //apparition de la fenêtre
        jCreditPage.setVisible(true);
        jCreditPage.requestFocusInWindow();
        jCreditPage.pack();
        jCreditPage.setResizable(false);
    }//GEN-LAST:event_jCreditMouseClicked

    private void jBackCreditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackCreditsMouseClicked
        jCreditPage.dispose();      //ferme la fenêtre
    }//GEN-LAST:event_jBackCreditsMouseClicked

    private void jShowButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowButtonMousePressed
        jShowPassword.setText(jPasswordField.getText());    //affichage du mdp masqué
    }//GEN-LAST:event_jShowButtonMousePressed

    private void jShowButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowButtonMouseReleased
        jShowPassword.setText("");  //enlève l'affichage du mdp
    }//GEN-LAST:event_jShowButtonMouseReleased

    private void jBackConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackConnexionMouseClicked
        jConnexionPage.dispose();   //ferme la fenêtre
    }//GEN-LAST:event_jBackConnexionMouseClicked

    private void jNewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNewAccountMouseClicked

        //apparition pour nouveau compte
        jLabel6.setText("CONFIRM PASSWORD :");
        jShowConfirm.setVisible(true);
        jConfirmPasswordField.setVisible(true);
        //changement pour nouveau compte
        jLabel3.setText("CREATE AN ACCOUNT");
        jNewAccount.setVisible(false);
    }//GEN-LAST:event_jNewAccountMouseClicked

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        jOkConnexion.setEnabled(true);  //permet de rendre le bouton utilisable une fois que quelquechose est rempli
        //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        // A MODIFIER UN PEU EN VRAI C PA OUF
        //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    }//GEN-LAST:event_jPasswordFieldKeyPressed

    private void jShowConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowConfirmMousePressed
        jShowConfirmPassword.setText(jConfirmPasswordField.getText());    //affichage du mdp masqué
    }//GEN-LAST:event_jShowConfirmMousePressed

    private void jShowConfirmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowConfirmMouseReleased
        jShowConfirmPassword.setText("");  //enlève l'affichage du mdp
    }//GEN-LAST:event_jShowConfirmMouseReleased

    private void jNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNewGameMouseClicked
        if (jNewGame.isEnabled()) {
            //initialisation fenêtre
            jConfigurationPage.setVisible(true);
            jConfigurationPage.requestFocus();
            jConfigurationPage.pack();
            jConfigurationPage.setResizable(false);
            

            //remplissage pseudos
            jPseudoLeft.setText(jPseudoField.getText());

            //ICI RAJOUTER PARTIE PSUEDO ALEATOIRE RIGHT
            jPseudoRight.setText("faire le pseudo");

        }


    }//GEN-LAST:event_jNewGameMouseClicked

    private void jColorLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorLeftActionPerformed
        String colorL = (String) jColorLeft.getSelectedItem();
        jPionImageLeft.setIcon(new ImageIcon("./img/pion" + colorL + "_1_6_clair.gif"));
    }//GEN-LAST:event_jColorLeftActionPerformed

    private void jColorRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorRightActionPerformed
        String colorR = (String) jColorRight.getSelectedItem();
        jPionImageRight.setIcon(new ImageIcon("./img/pion" + colorR + "_1_6_clair.gif"));
    }//GEN-LAST:event_jColorRightActionPerformed

    private void jStartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStartButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jStartButtonMouseClicked

    private void jBackConfigurationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackConfigurationMouseClicked
        jConfigurationPage.dispose();
        jMenuPrincipal.setVisible(true);
        jSelecLeft.setSelectedIndex(0);
        jSelecRight.setSelectedIndex(0);
        jColorLeft.setSelectedIndex(0);
        jColorRight.setSelectedIndex(0);
        jPionImageLeft.setIcon(new ImageIcon());
        jPionImageRight.setIcon(new ImageIcon());
    }//GEN-LAST:event_jBackConfigurationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame menuP = new Interface();
                menuP.setVisible(true);
                menuP.setResizable(false);  //empêche la redimension
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jAdvancedCheck;
    private javax.swing.JPanel jBG;
    private javax.swing.JButton jBackConfiguration;
    private javax.swing.JButton jBackConnexion;
    private javax.swing.JButton jBackCredits;
    private javax.swing.JComboBox<String> jColorLeft;
    private javax.swing.JComboBox<String> jColorRight;
    private javax.swing.JPanel jConfigLeft;
    private javax.swing.JPanel jConfigRight;
    private javax.swing.JFrame jConfigurationPage;
    private javax.swing.JPasswordField jConfirmPasswordField;
    private javax.swing.JButton jConnexion;
    private javax.swing.JFrame jConnexionPage;
    private javax.swing.JButton jContinue;
    private javax.swing.JButton jCredit;
    private javax.swing.JFrame jCreditPage;
    private javax.swing.JLabel jErrorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMenuPrincipal;
    private javax.swing.JButton jNewAccount;
    private javax.swing.JButton jNewGame;
    private javax.swing.JButton jOkConnexion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel jPionImageLeft;
    private javax.swing.JLabel jPionImageRight;
    private javax.swing.JButton jPrevious;
    private javax.swing.JLabel jPseudo;
    private javax.swing.JTextField jPseudoField;
    private javax.swing.JLabel jPseudoLeft;
    private javax.swing.JLabel jPseudoRight;
    private javax.swing.JComboBox<String> jSelecLeft;
    private javax.swing.JComboBox<String> jSelecRight;
    private javax.swing.JButton jShowButton;
    private javax.swing.JButton jShowConfirm;
    private javax.swing.JLabel jShowConfirmPassword;
    private javax.swing.JLabel jShowPassword;
    private javax.swing.JButton jStartButton;
    private javax.swing.JLabel jTitre;
    // End of variables declaration//GEN-END:variables
}
